H_SHARED_UID = "SK_ID_CURR"
H_SHARED_TARGET = "TARGET"
H_SHARED_AMOUNT = "AMT_CREDIT"

H_STREAMLIT_FEATS = ["EXT_SOURCE_3","EXT_SOURCE_2"]

APISCOREHEADER = "score"
APIGRANTEDHEADER = "granted_or_not"
APIITEMIDHEADER = "item_id"

STREAMLITDIR="Streamlit/"
STREAMLITPICTURESDIR=f"{STREAMLITDIR}Pictures/"
STREAMLITDATADIR=f"{STREAMLITDIR}Data/"

APIDIR="API/"
APIDATADIR=f"{APIDIR}Data/"

SHAREDRESOURCESDIR="SharedResources/"
SHAREDRESOURCESTYPESDIR=f"{SHAREDRESOURCESDIR}Types/"
SHAREDRESOURCESMODELDIR=f"{SHAREDRESOURCESDIR}Model/"

MAINDATATYPESFILENAME = "maindatatypes.pkl"

STREAMLITNBCUSTOMERS = 500
APINBFEATURES = 40

FINALMODELTHRESHOLDPCT = 50

URL_API = "http://127.0.0.1:8000/"
URL_DASHBOARD = "http://localhost:8501"

