H_SHARED_UID = "SK_ID_CURR"
H_SHARED_TARGET = "TARGET"
H_SHARED_AMOUNT = "AMT_CREDIT"


APISCOREHEADER = "score"
APIGRANTEDHEADER = "granted_or_not"
APIITEMIDHEADER = "item_id"

STREAMLITDIR="Streamlit/"
STREAMLITDATADIR=f"{STREAMLITDIR}Data/"
STREAMLITPICTURESDIR=f"{STREAMLITDIR}Pictures/"

APIDIR="API/"
APIDATADIR=f"{APIDIR}Data/"
APIMODELDIR=f"{APIDIR}Model/"

SHAREDRESOURCESDIR="SharedResources/"
SHAREDRESOURCESTYPESDIR=f"{SHAREDRESOURCESDIR}Types/"

MAINDATATYPESFILENAME = "maindatatypes.pkl"

STREAMLITNBCUSTOMERS = 500
APINBFEATURES = 40

